project:
  type: website

website:
  title: "AI Tutorials"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: lstm.qmd
        text: LSTM
      - href: transformers.qmd
        text: Transformers

format:
  html:
    theme: cosmo
    toc: true
