project:
  type: website

website:
  title: "<span style='color:#3B82F6;font-weight:bold;'>🤖 AI Vault</span>"
  sidebar:
    style: floating
    search: true
    contents:
      - index.qmd
      - lstm.qmd
      - rnn.qmd
      - cnn.qmd
      - transformer.qmd

format:
  html:
    theme: cosmo
    toc: true
    code-fold: false
